# Generated by Django 4.2.20 on 2025-03-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestdataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('res_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Restdata',
        ),
    ]
