# Generated by Django 4.2.20 on 2025-03-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_service', '0002_restdatatable_delete_restdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resId', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('data', models.JSONField()),
            ],
        ),
    ]
