services:
    web-tomato:
        build: .
        container_name: web-container
        command: >
            sh -c "sleep 5 &&
                   python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            - DATABASE_NAME=ResData
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=Chandu@832000
            - DATABASE_HOST=db
            - DATABASE_PORT=5432

    db:
        image: postgres:17
        container_name: django-db
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=Chandu@832000
            - POSTGRES_DB=ResData
        ports:
            - "5433:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    pgdata: